name: Python CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install dependencies if necessary
        # pip install -r requirements.txt

    - name: Build the calculator application
      run: |
        echo "Building the application..."
        # No interactive run; simply build or validate structure
        python -m py_compile calculator.py  # Compiles the Python file to validate syntax
    
    - name: Run tests
      run: |
        python -m unittest discover
